import type { Exercise, RegionId, RegionInfo } from './types'

export const REGIONS: RegionInfo[] = [
  { id: 'testa', label: 'Testa', short: 'Testa', concern: 'Tensão e linhas de expressão' },
  { id: 'olhos', label: 'Olhos e olheiras', short: 'Olhos', concern: 'Cansaço percebido e inchaço' },
  { id: 'bochechas', label: 'Bochechas', short: 'Bochechas', concern: 'Consciência muscular do sorriso' },
  { id: 'bigode', label: 'Bigode chinês', short: 'Bigode chinês', concern: 'Região entre nariz e lábios' },
  { id: 'mandibula', label: 'Mandíbula', short: 'Mandíbula', concern: 'Tensão de mastigação e contorno' },
  { id: 'papada', label: 'Papada', short: 'Papada', concern: 'Região abaixo do queixo' },
  { id: 'pescoco', label: 'Pescoço', short: 'Pescoço', concern: 'Relaxamento e aplicação sem fricção' },
]

export const regionById = (id: RegionId) => REGIONS.find((r) => r.id === id)!

/**
 * As 14 fichas do capítulo 3 — "Exercícios passo a passo por região".
 * Doses conservadoras para começar; objetivos cosméticos, nunca promessas anatômicas.
 */
export const EXERCISES: Exercise[] = [
  {
    id: 'testa-alisamento',
    number: '3.1',
    region: 'testa',
    title: 'Alisamento suave para as têmporas',
    goal: 'Criar uma aparência momentaneamente mais descansada e ajudar a perceber tensão na testa; a ideia de suavizar linhas é uma alegação editorial, não um apagamento de rugas.',
    position:
      'Sentado ou em pé, cabeça sobre a coluna, olhos relaxados e dentes sem contato. Coloque as pontas dos dedos no centro da testa, apontadas para cima ou levemente para dentro.',
    execution:
      'Pressione apenas o suficiente para manter contato. Deslize do centro em direção às têmporas, em linha horizontal suave. Retire os dedos e reinicie; não arraste a pele nem faça movimentos rápidos.',
    breathing: 'Inspire ao preparar as mãos; expire lentamente durante o deslizamento. Continue respirando de modo natural.',
    reps: '30 segundos, conforme protocolo cronometrado de uma fonte; a versão da Marie Claire propõe dez passagens, sem determinar o tempo de cada uma.',
    frequency:
      'Comece três vezes por semana. Se não houver vermelhidão ou desconforto, pode chegar a uma passagem curta por dia; não é necessário fazer várias séries.',
    sensation: 'Contato, calor discreto ou relaxamento. A pele não deve parecer esticada depois.',
    stopSigns:
      'Ardor, dor, puxão, vermelhidão persistente, dor de cabeça ou aumento da tensão. Evite transformar o movimento em contrações repetidas da testa: a Vogue alerta que execução incorreta pode tornar linhas superiores mais visíveis.',
    practiceSec: 30,
    cues: ['Dedos no centro da testa', 'Deslize até as têmporas', 'Levante, reposicione, repita', 'Expire no deslizamento'],
    minWeek: 1,
    avoidIf: [],
    cautionIf: ['peleCrise'],
    sources: [1, 6, 8],
  },
  {
    id: 'testa-sobrancelhas',
    number: '3.2',
    region: 'testa',
    title: 'Pressão entre sobrancelhas',
    optional: true,
    goal: 'Favorecer uma pausa consciente na área frequentemente contraída; não promete remover a linha entre as sobrancelhas.',
    position: 'Mantenha o olhar macio. Apoie um polegar limpo entre as sobrancelhas, sem pressionar o nariz ou o globo ocular.',
    execution:
      'Faça uma passagem para cima e depois uma passagem curta para fora, como no método de Collins. Em vez de friccionar, levante o dedo, reposicione e repita.',
    breathing: 'Expire durante a passagem e solte a mão na inspiração.',
    reps: 'Cinco passagens totais, em cerca de 30 segundos.',
    frequency: 'Três a cinco vezes por semana; pule em dias de irritação ou após produto sensibilizante.',
    sensation: 'Redução de aperto local, nunca pressão dolorosa.',
    stopSigns:
      'Dor na testa ou nos olhos, visão turva, ardor, sensação de pele sendo beliscada ou vontade involuntária de franzir mais.',
    practiceSec: 30,
    cues: ['Polegar entre as sobrancelhas', 'Passagem para cima, depois para fora', 'Levante e reposicione', '5 passagens no total'],
    minWeek: 1,
    avoidIf: [],
    cautionIf: ['olhos', 'peleCrise'],
    sources: [3],
  },
  {
    id: 'olhos-pena',
    number: '3.3',
    region: 'olhos',
    title: 'Círculos de toque “como uma pena”',
    goal: 'Fazer uma pausa para cansaço percebido e trabalhar suavemente a aparência de inchaço; não clareia, por si só, toda olheira.',
    position:
      'Sente-se com a cabeça neutra. Use os dedos anulares ou mínimos, que tendem a aplicar menos força. Toque o osso ao redor dos olhos, não o globo ocular.',
    execution:
      'Comece próximo à sobrancelha interna, toque levemente em direção à extremidade, passe pelas têmporas e siga acima das maçãs do rosto até retornar ao canto interno. Não puxe a pálpebra, não esfregue e não pressione a bolsa sob o olho.',
    breathing: 'Mantenha respiração normal; expire quando a mão se deslocar e não prenda o ar.',
    reps: '30 segundos, uma única sequência. A Healthline descreve toques muito leves e pressão nas têmporas por alguns segundos.',
    frequency: 'No máximo uma vez ao dia para esta sequência. Comece em dias alternados se seus olhos forem muito sensíveis.',
    sensation: 'Toque quase imperceptível e possível relaxamento; não procure calor intenso ou vermelhidão.',
    stopSigns:
      'Dor ocular, ardor forte, lacrimejamento persistente, inchaço importante, secreção, alteração visual ou irritação que permaneça após a prática.',
    note: {
      title: 'Por que isso não “trata” olheiras?',
      text: 'Olheiras podem envolver pigmentação, vasos aparentes, sombra anatômica, inchaço, ressecamento, genética, sono e outras causas. Uma massagem pode mudar temporariamente a sensação ou o inchaço, mas não identifica nem corrige todas essas causas.',
    },
    practiceSec: 30,
    cues: ['Dedo anelar, toque de pena', 'Sobre o osso, nunca no globo ocular', 'Sobrancelha → têmpora → maçã do rosto', 'Uma única volta lenta'],
    minWeek: 1,
    avoidIf: ['olhos'],
    cautionIf: ['peleCrise'],
    sources: [4, 8],
  },
  {
    id: 'olhos-rastreamento',
    number: '3.4',
    region: 'olhos',
    title: 'Rastreamento sem mover a cabeça',
    goal: 'Criar um exercício de atenção e mobilidade do olhar sem pressionar a pele; qualquer melhora na sensação de fadiga deve ser entendida como possível e temporária.',
    position: 'Mantenha cabeça, pescoço e rosto quietos. Fixe um ponto à frente; a mão pode repousar na testa sem empurrar.',
    execution:
      'Olhe para a direita e volte ao centro; para a esquerda e volte; para o teto e volte; para o chão e volte. Feche os olhos por cinco segundos e reabra sem apertar as pálpebras.',
    breathing: 'Respire de forma contínua. Pisque quando precisar.',
    reps: 'Faça a sequência duas vezes, com a pausa de cinco segundos ao final, conforme a proposta editorial consultada.',
    frequency: 'Uma vez ao dia ou em dias alternados. Não combine com várias rotinas de contração ocular.',
    sensation: 'Movimento confortável, sem esforço de foco.',
    stopSigns: 'Tontura, náusea, visão dupla ou turva, dor, cefaleia ou desconforto ocular persistente.',
    practiceSec: 30,
    cues: ['Cabeça parada', 'Direita, centro, esquerda, centro', 'Teto, centro, chão, centro', 'Feche os olhos por 5 segundos'],
    minWeek: 2,
    avoidIf: ['olhos'],
    cautionIf: [],
    sources: [9],
  },
  {
    id: 'bochechas-ar',
    number: '3.5',
    region: 'bochechas',
    title: 'Transferência de ar',
    goal: 'Perceber e ativar suavemente a musculatura das bochechas; “dar volume”, firmar ou levantar são alegações de beleza, não resultado garantido.',
    position:
      'Sente-se com a mandíbula solta e lábios fechados sem apertar. Encha as duas bochechas com ar; não faça força para estufá-las ao máximo.',
    execution:
      'Transfira o ar lentamente de uma bochecha para a outra, como um bochecho. Mantenha as mãos afastadas ou apenas apoie-as sem empurrar a pele. Faça pausas para respirar pelo nariz.',
    breathing:
      'Inspire pelo nariz antes de começar; interrompa a transferência para respirar quando necessário. Não retenha o ar até ficar ofegante.',
    reps: '30 segundos, conforme a versão da Versatille; a Women’s Best descreve blocos de um minuto e até cinco a dez sequências, mas não recomendamos essa dose para iniciantes.',
    frequency: 'Três vezes por semana no primeiro mês; se a mandíbula permanecer confortável, até uma vez ao dia.',
    sensation: 'Esforço leve nas bochechas e boca, sem cansaço que persista.',
    stopSigns: 'Estalo doloroso, travamento, dor na mandíbula ou ouvido, cãibra, tontura ou sensação de falta de ar.',
    practiceSec: 30,
    cues: ['Bochechas cheias, sem estufar ao máximo', 'Passe o ar de um lado ao outro', 'Pause para respirar pelo nariz'],
    minWeek: 2,
    avoidIf: ['atm'],
    cautionIf: [],
    sources: [10, 11],
  },
  {
    id: 'bochechas-sorriso',
    number: '3.6',
    region: 'bochechas',
    title: 'Sorriso protegido',
    goal: 'Praticar uma expressão ampla com consciência e observar como as bochechas participam do sorriso; não promete corrigir flacidez.',
    position: 'Esconda os dentes com os lábios e forme um “O” pequeno. Mantenha a nuca longa e os olhos relaxados.',
    execution:
      'Amplie o sorriso sem mostrar os dentes e relaxe. Depois, se não houver desconforto, apoie o indicador no centro do queixo e mova a mandíbula apenas alguns milímetros para cima e para baixo; não force a abertura.',
    breathing: 'Inspire no “O”, expire no sorriso e solte a mandíbula entre repetições.',
    reps: 'Seis sorrisos; a etapa da mandíbula, no máximo duas repetições, seguindo a proposta da Marie Claire.',
    frequency:
      'Até três vezes por semana no início; a matéria original associava a rotina completa a 20 minutos, seis dias por semana, mas esse volume não é obrigatório.',
    sensation: 'Ativação leve das bochechas e relaxamento ao soltar.',
    stopSigns: 'Dor na articulação, apertamento dental, espasmo, cansaço intenso ou tensão na nuca.',
    practiceSec: 45,
    cues: ['Lábios cobrindo os dentes, “O” pequeno', 'Amplie o sorriso e relaxe', '6 sorrisos', 'Mandíbula: no máximo 2 movimentos curtos'],
    minWeek: 3,
    avoidIf: [],
    cautionIf: ['atm'],
    sources: [6],
  },
  {
    id: 'bigode-resistencia',
    number: '3.7',
    region: 'bigode',
    title: 'Resistência mínima na dobra nasolabial',
    goal: 'Aumentar a consciência da região entre nariz e lábios durante o sorriso; a alegação de “desbotar” o sulco é opinião de beleza, não correção estrutural.',
    position:
      'Sorria de forma confortável, sem forçar os olhos. Lave as mãos e coloque as pontas dos dedos sobre a dobra, nunca dentro da narina ou sobre pele ferida.',
    execution:
      'Ofereça uma resistência muito pequena com os dedos enquanto eleva a musculatura do sorriso. O dedo acompanha a pele; não puxe para cima, não belisque e não tente “apagar” a marca com pressão.',
    breathing: 'Respire pelo nariz e relaxe a boca entre cada repetição.',
    reps: 'Comece com dez repetições lentas. A Women’s Best publica pelo menos 20, mas a dose menor é suficiente para testar tolerância.',
    frequency: 'Três vezes por semana; no máximo uma vez ao dia se não houver tensão.',
    sensation: 'Contração leve ao sorrir e contato superficial dos dedos.',
    stopSigns: 'Dor, pinçamento, vermelhidão que não diminui, fissura, formigamento ou aumento do sulco pela tração.',
    practiceSec: 60,
    cues: ['Dedos sobre a dobra, sem puxar', 'Sorria contra uma resistência mínima', 'Relaxe a boca entre repetições', '10 repetições lentas'],
    minWeek: 3,
    avoidIf: [],
    cautionIf: ['peleCrise'],
    sources: [6],
  },
  {
    id: 'bigode-lingua',
    number: '3.8',
    region: 'bigode',
    title: 'Círculos internos com a língua',
    optional: true,
    goal: 'Explorar uma prática editorial que movimenta a musculatura ao redor da boca sem arrastar a pele externa; não há prova de redução do sulco.',
    position:
      'Sente-se e higienize a boca. Mantenha lábios fechados com suavidade e coloque a língua dentro da boca, atrás da linha dos lábios.',
    execution:
      'Faça pequenos círculos pelo lado interno, começando próximo ao nariz, sobre a linha labial. Use amplitude discreta e pare se houver cansaço ou dor na articulação.',
    breathing: 'Respire pelo nariz; faça uma pausa se a saliva ou a respiração ficarem desconfortáveis.',
    reps: 'Cinco círculos no sentido horário e cinco no anti-horário de cada lado, conforme Good Housekeeping.',
    frequency: 'Uma vez ao dia no máximo; dias alternados são suficientes no começo.',
    sensation: 'Movimento leve dentro da boca e fadiga mínima.',
    stopSigns: 'Dor dentária, ferida na mucosa, travamento, estalo doloroso ou tensão crescente.',
    practiceSec: 45,
    sided: true,
    cues: ['Lábios fechados com suavidade', 'Língua atrás da linha dos lábios', '5 círculos horários, 5 anti-horários', 'Amplitude discreta'],
    minWeek: 3,
    avoidIf: ['atm'],
    cautionIf: [],
    sources: [9],
  },
  {
    id: 'mandibula-deslizamento',
    number: '3.9',
    region: 'mandibula',
    title: 'Deslizamento manual da linha mandibular',
    goal: 'Ajudar a perceber tensão e criar aparência momentaneamente mais descansada no contorno; não redefine os ossos, não reduz gordura localizada e não substitui cuidado para dor mandibular.',
    position: 'Mantenha boca entreaberta, dentes sem se tocar. Apoie dois dedos no centro do queixo.',
    execution:
      'Faça círculos pequenos e lentos ao longo da mandíbula, do queixo até diante da orelha e de volta. A versão em gancho pode ser feita com polegar e indicador em “V”, mas apenas com pressão leve — não comprima a articulação.',
    breathing: 'Expire ao conduzir para a orelha; inspire ao retornar.',
    reps: '30 segundos por lado. Uma fonte descreve oito passagens por lado com pressão média, mas iniciantes devem começar mais leve e com menos passagens.',
    frequency: 'Três a cinco vezes por semana.',
    sensation: 'Contato, calor discreto e relaxamento dos músculos de mastigação.',
    stopSigns: 'Dor na frente da orelha, estalo doloroso, travamento, dor de dente, dormência ou dor de cabeça.',
    practiceSec: 60,
    sided: true,
    cues: ['Dentes sem se tocar', 'Círculos pequenos do queixo à orelha', 'Pressão leve, nunca na articulação', 'Expire indo, inspire voltando'],
    minWeek: 1,
    avoidIf: ['atm'],
    cautionIf: [],
    sources: [3],
  },
  {
    id: 'mandibula-elevacao',
    number: '3.10',
    region: 'mandibula',
    title: 'Pescoço neutro e levantamento curto da cabeça',
    optional: true,
    goal: 'Trabalhar suavemente a percepção da musculatura sob o queixo; qualquer mudança de contorno é incerta e não deve ser prometida.',
    position:
      'Deite-se de costas, pressione a língua no céu da boca e mantenha o tronco apoiado. O pescoço deve começar confortável, sem colchonete que force a cabeça.',
    execution:
      'Leve o queixo em direção ao peito e eleve a cabeça cerca de 5 cm, sem projetar o queixo e sem levantar os ombros. Desça devagar e descanse.',
    breathing: 'Expire ao elevar, inspire ao descer. Nunca prenda o ar.',
    reps: 'Comece com uma série de cinco, não com as três séries de dez sugeridas pela Healthline; só progrida se não houver tensão cervical.',
    frequency:
      'Uma vez por semana no primeiro mês, ou não faça se houver qualquer histórico cervical sem liberação profissional.',
    sensation: 'Esforço leve no pescoço, nunca compressão ou tremor intenso.',
    stopSigns:
      'Dor cervical, formigamento, tontura, dor de cabeça, náusea ou piora ao virar a cabeça. A fonte recomenda parar e conversar com médico diante de preocupação.',
    practiceSec: 45,
    cues: ['Deitada, língua no céu da boca', 'Queixo em direção ao peito', 'Eleve a cabeça ~5 cm e desça devagar', '1 série de 5'],
    minWeek: 5,
    avoidIf: ['cervical'],
    cautionIf: ['atm'],
    sources: [12],
  },
  {
    id: 'papada-projecao',
    number: '3.11',
    region: 'papada',
    title: 'Projeção suave da mandíbula',
    optional: true,
    goal: 'Alongar momentaneamente a região sob o queixo e explorar uma contração; não elimina gordura, pele excedente ou papada. A Healthline afirma que não há evidência científica de que exercícios eliminem a papada.',
    position:
      'Sente-se com o tronco ereto. Incline a cabeça para trás apenas o suficiente para olhar para o teto; não comprima a nuca.',
    execution:
      'Projete a mandíbula inferior para a frente até um alongamento confortável sob o queixo. Relaxe a mandíbula e volte ao neutro. Não empurre os dentes nem leve a cabeça ao limite.',
    breathing: 'Expire durante a projeção, inspire ao retornar.',
    reps: 'Segure contando até dez e faça até cinco repetições no começo, em vez das dez publicadas.',
    frequency: 'Duas a três vezes por semana; não transforme a orientação genérica de “várias vezes ao dia” em obrigação.',
    sensation: 'Alongamento leve e simétrico sob o queixo.',
    stopSigns: 'Dor na cervical, mandíbula ou ouvido, estalo doloroso, tontura, visão alterada ou dificuldade de engolir.',
    practiceSec: 60,
    cues: ['Olhe para o teto sem comprimir a nuca', 'Projete a mandíbula para a frente', 'Segure contando até 10', 'Até 5 repetições'],
    minWeek: 5,
    avoidIf: ['cervical', 'atm'],
    cautionIf: [],
    sources: [7],
  },
  {
    id: 'papada-apoio',
    number: '3.12',
    region: 'papada',
    title: 'Apoio dos dedos e batidas delicadas',
    goal: 'Proporcionar toque e consciência da região, com possível sensação temporária de aquecimento; não promete drenagem, afinamento ou lifting.',
    position:
      'Para a parte A, apoie o cotovelo com a outra mão, coloque as pontas dos dedos sob o queixo e olhe para baixo. Para a parte B, mantenha o pescoço neutro.',
    execution:
      'Na parte A, deixe o queixo repousar levemente sobre os dedos por três respirações; não empurre com força. Na parte B, alterne batidas delicadas sob o queixo com a ponta dos dedos, como um toque de chuva.',
    breathing: 'Três respirações lentas na parte A; respiração natural na parte B.',
    reps: 'Parte A por três respirações e parte B por 15 segundos, como na prática editorial consultada.',
    frequency: 'Até uma vez ao dia, cinco dias por semana, com pelo menos dois dias de descanso.',
    sensation: 'Contato leve e aquecimento discreto, sem marcas.',
    stopSigns: 'Hematoma, petéquias, dor, formigamento, pele rompida ou aumento de inchaço.',
    practiceSec: 45,
    cues: ['A: queixo repousa nos dedos por 3 respirações', 'B: batidas de “chuva” por 15 segundos', 'Sem empurrar com força'],
    minWeek: 3,
    avoidIf: [],
    cautionIf: ['cervical', 'peleCrise'],
    sources: [11],
  },
  {
    id: 'pescoco-deslizamento',
    number: '3.13',
    region: 'pescoco',
    title: 'Deslizamento até a clavícula',
    goal: 'Relaxar a região e aplicar produto sem fricção; a ideia de “drenar”, firmar ou rejuvenescer é alegação editorial, não fato clínico.',
    position: 'Sente-se com ombros baixos e cabeça neutra ou apenas levemente inclinada para trás se isso for confortável.',
    execution:
      'Com as mãos espalmadas ou polpas dos dedos, deslize do alto do pescoço até as clavículas. Use produto suficiente para a mão correr, não para puxar a pele. Termine pressionando a clavícula por um segundo, sem cavar.',
    breathing: 'Expire no deslizamento e inspire ao reposicionar.',
    reps: '30 segundos, conforme protocolo descrito pela Healthline.',
    frequency: 'Três a cinco vezes por semana; se a pele for sensível, comece duas vezes.',
    sensation: 'Deslizamento confortável e relaxamento.',
    stopSigns: 'Dor, pressão na garganta, falta de ar, tontura, formigamento ou vermelhidão que persista.',
    practiceSec: 30,
    cues: ['Mãos espalmadas no alto do pescoço', 'Deslize até as clavículas', 'Pressione a clavícula por 1 segundo', 'Expire no deslizamento'],
    minWeek: 1,
    avoidIf: [],
    cautionIf: ['cervical'],
    sources: [8],
  },
  {
    id: 'pescoco-extensao',
    number: '3.14',
    region: 'pescoco',
    title: 'Extensão lateral',
    optional: true,
    goal: 'Praticar amplitude consciente do pescoço e alongamento leve, sem promessa de apagar linhas.',
    position:
      'Apenas se não houver problema cervical conhecido e se a posição neutra for confortável. Mantenha os ombros baixos e olhe para a frente.',
    execution:
      'Vire a cabeça para a direita sem elevar o ombro; incline levemente para trás até perceber alongamento, sem forçar. Volte ao centro e repita à esquerda. Não puxe a pele com os dedos.',
    breathing: 'Respire continuamente; expire ao entrar no alongamento e inspire ao voltar.',
    reps: 'Segure 6–8 segundos por lado, até três vezes, conforme a proposta editorial da Versatille.',
    frequency: 'Comece uma vez por semana. Se houver histórico cervical, substitua pelo deslizamento e peça orientação profissional.',
    sensation: 'Alongamento leve, nunca compressão.',
    stopSigns:
      'Dor, tontura, formigamento, dor irradiada, desequilíbrio ou desconforto que permanece após voltar ao neutro.',
    practiceSec: 50,
    sided: true,
    cues: ['Ombros baixos', 'Vire para o lado e incline levemente para trás', 'Segure 6–8 segundos', 'Volte ao centro e troque de lado'],
    minWeek: 5,
    avoidIf: ['cervical'],
    cautionIf: [],
    sources: [11],
  },
]

export const exerciseById = (id: string) => EXERCISES.find((e) => e.id === id)
